name: Build/release Electron app

on:
  repository_dispatch:
    types: [release]
    
jobs:
  release:
    permissions:
      contents: write
      
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out project
        uses: actions/checkout@v4
        with:
          repository: egoist/chatwise
          token: ${{ secrets.GH_TOKEN_FOR_CHECKOUT }}
          ref: ${{ github.event.client_payload.sha }}

      - uses: pnpm/action-setup@v4
        with:
          cache: true
          
      - name: setup bun (for running scripts)
        uses: oven-sh/setup-bun@v2      
        
      - name: Install posthog-cli
        run: |
          bun ./ensure-posthog.ts

      - name: Install Dependencies
        run: pnpm install

      - name: test
        run: pnpm --filter desktop-new test

      - name: build and release
        run: pnpm --filter desktop-new release
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          CSC_LINK: ${{ secrets.APPLE_CERTIFICATE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

