name: "Sync Release"

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Sync release to S3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bun ./sync-release.ts
